---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[nodejs::nodejs_from_package]
      - recipe[nodejs::npm]
      - recipe[slc::install_dev]
      - recipe[ctl_test::ctl]
    attributes:
  - name: production
    run_list:
      - recipe[nodejs::nodejs_from_package]
      - recipe[nodejs::npm]
      - recipe[slc::install_production]
    attributes:

